In [1]:
import pandas as pd

In [2]:
d1 = [["Max",99],["Cassie",95],["Nicole",78]]
d1

[['Max', 99], ['Cassie', 95], ['Nicole', 78]]

In [3]:
pd.DataFrame(d1,columns=["Name","Marks"])

     Name  Marks
0     Max     99
1  Cassie     95
2  Nicole     78

In [4]:
d2 = {"a":[6,7,8],"b":[7,8,9]}
pd = pd.DataFrame(d2)
pd

   a  b
0  6  7
1  7  8
2  8  9

In [1]:
import numpy as np
import pandas as pd

In [4]:
d3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(d3,columns=[0,1,2])
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [7]:
df.columns

Index([0, 1, 2], dtype='int64')

In [8]:
pd.read_excel("table.xlsx")

       Name School   Marks
0       max     PPS     69
1       sam     MPS     66
2      bill     TTS     77
3  whiteley     FPS     88
4      marx     JPS     46

In [13]:
df = pd.read_json("data.json")
df

   name language
0  Noms   Python
1  Liam     java

In [14]:
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [15]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [16]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [18]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [19]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [20]:
df.shape

(244, 7)