In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("filter.xlsx")
df

    name school  gender  marks
0   Alex    SSS    Male     88
1    Sam    FRD    Male     96
2   Rose    GPS  Female     87
3  Ember    TOS  Female     86
4  Jason    PSP    Male     99

In [3]:
df.sort_values("marks")

    name school  gender  marks
3  Ember    TOS  Female     86
2   Rose    GPS  Female     87
0   Alex    SSS    Male     88
1    Sam    FRD    Male     96
4  Jason    PSP    Male     99

In [5]:
df2 = df.sort_values("marks",ascending = False).copy()

In [6]:
df2

    name school  gender  marks
4  Jason    PSP    Male     99
1    Sam    FRD    Male     96
0   Alex    SSS    Male     88
2   Rose    GPS  Female     87
3  Ember    TOS  Female     86

In [8]:
df2.reset_index()

   index   name school  gender  marks
0      4  Jason    PSP    Male     99
1      1    Sam    FRD    Male     96
2      0   Alex    SSS    Male     88
3      2   Rose    GPS  Female     87
4      3  Ember    TOS  Female     86

In [9]:
df2

    name school  gender  marks
4  Jason    PSP    Male     99
1    Sam    FRD    Male     96
0   Alex    SSS    Male     88
2   Rose    GPS  Female     87
3  Ember    TOS  Female     86

In [10]:
df2.reset_index(drop = True)

    name school  gender  marks
0  Jason    PSP    Male     99
1    Sam    FRD    Male     96
2   Alex    SSS    Male     88
3   Rose    GPS  Female     87
4  Ember    TOS  Female     86

In [11]:
df2.reset_index(drop = True,inplace = True)

In [12]:
df2

    name school  gender  marks
0  Jason    PSP    Male     99
1    Sam    FRD    Male     96
2   Alex    SSS    Male     88
3   Rose    GPS  Female     87
4  Ember    TOS  Female     86

In [14]:
df2["Rank"] = df2["marks"].rank(ascending = False)
df2

    name school  gender  marks  Rank
0  Jason    PSP    Male     99   1.0
1    Sam    FRD    Male     96   2.0
2   Alex    SSS    Male     88   3.0
3   Rose    GPS  Female     87   4.0
4  Ember    TOS  Female     86   5.0

In [15]:
df2 = df2[["marks","gender","name","school"]]
df2

   marks  gender   name school
0     99    Male  Jason    PSP
1     96    Male    Sam    FRD
2     88    Male   Alex    SSS
3     87  Female   Rose    GPS
4     86  Female  Ember    TOS