In [4]:
import pandas as pd

In [5]:
df.isnull() #jaha bhi null waha true aayega

    Name  School   Marks
0  False    False  False
1  False    False  False
2  False    False  False
3  False    False  False
4  False    False  False

In [6]:
df.isnull().sum()

Name       0
School     0
Marks      0
dtype: int64

In [6]:
df = pd.read_excel("exp.xlsx")
df

    name school  gender  marks
0   Alex    NaN    Male   88.0
1    Sam    FRD    Male   96.0
2   Rose    GPS     NaN   87.0
3  Ember    TOS  Female    NaN
4  Jason    PSP    Male   99.0

In [10]:
df.isnull()

    name  school  gender  marks
0  False    True   False  False
1  False   False   False  False
2  False   False    True  False
3  False   False   False   True
4  False   False   False  False

In [11]:
df.isnull().sum()

name      0
school    1
gender    1
marks     1
dtype: int64

In [12]:
df.dropna()

    name school gender  marks
1    Sam    FRD   Male   96.0
4  Jason    PSP   Male   99.0

In [13]:
df.dropna(axis=1)

    name
0   Alex
1    Sam
2   Rose
3  Ember
4  Jason

In [14]:
df.fillna(0)

    name school  gender  marks
0   Alex      0    Male   88.0
1    Sam    FRD    Male   96.0
2   Rose    GPS       0   87.0
3  Ember    TOS  Female    0.0
4  Jason    PSP    Male   99.0

In [15]:
df.ffill()

    name school  gender  marks
0   Alex    NaN    Male   88.0
1    Sam    FRD    Male   96.0
2   Rose    GPS    Male   87.0
3  Ember    TOS  Female   87.0
4  Jason    PSP    Male   99.0

In [16]:
df.bfill()

    name school  gender  marks
0   Alex    FRD    Male   88.0
1    Sam    FRD    Male   96.0
2   Rose    GPS  Female   87.0
3  Ember    TOS  Female   99.0
4  Jason    PSP    Male   99.0

In [17]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [19]:
df.drop_duplicates()

    name school  gender  marks
0   Alex    NaN    Male   88.0
1    Sam    FRD    Male   96.0
2   Rose    GPS     NaN   87.0
3  Ember    TOS  Female    NaN
4  Jason    PSP    Male   99.0

In [20]:
df['name'].str.lower()

0     alex
1      sam
2     rose
3    ember
4    jason
Name: name, dtype: object

In [21]:
df['school'].str.contains('GPS',case=False)

0      NaN
1    False
2     True
3    False
4    False
Name: school, dtype: object

In [23]:
df['name'].str.split("@")

0     [Alex]
1      [Sam]
2     [Rose]
3    [Ember]
4    [Jason]
Name: name, dtype: object

In [25]:
type(df['name'].str.split("@")[0])

list

In [26]:
df

    name school  gender  marks
0   Alex    NaN    Male   88.0
1    Sam    FRD    Male   96.0
2   Rose    GPS     NaN   87.0
3  Ember    TOS  Female    NaN
4  Jason    PSP    Male   99.0

In [7]:
df

    name school  gender  marks
0   Alex    NaN    Male   88.0
1    Sam    FRD    Male   96.0
2   Rose    GPS     NaN   87.0
3  Ember    TOS  Female    NaN
4  Jason    PSP    Male   99.0

In [8]:
df["grade"] = df["marks"].apply(lambda x: "A" if x>90 else "B")
df

    name school  gender  marks grade
0   Alex    NaN    Male   88.0     B
1    Sam    FRD    Male   96.0     A
2   Rose    GPS     NaN   87.0     B
3  Ember    TOS  Female    NaN     B
4  Jason    PSP    Male   99.0     A

In [11]:
df["name"].replace({"Sam": "Sams" })
df

    name school  gender  marks grade
0   Alex    NaN    Male   88.0     B
1    Sam    FRD    Male   96.0     A
2   Rose    GPS     NaN   87.0     B
3  Ember    TOS  Female    NaN     B
4  Jason    PSP    Male   99.0     A