In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
df['tip']

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [6]:
df['tip'][2]

np.float64(3.5)

In [7]:
df[['total_bill','day']]

     total_bill   day
0         16.99   Sun
1         10.34   Sun
2         21.01   Sun
3         23.68   Sun
4         24.59   Sun
..          ...   ...
239       29.03   Sat
240       27.18   Sat
241       22.67   Sat
242       17.82   Sat
243       18.78  Thur

[244 rows x 2 columns]

In [8]:
df.loc[1]

total_bill     10.34
tip             1.66
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 1, dtype: object

In [9]:
df.iloc[1]

total_bill     10.34
tip             1.66
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 1, dtype: object

In [10]:
df.loc[2,'total_bill']

np.float64(21.01)

In [12]:
df.iloc[2,0]

np.float64(21.01)

In [13]:
df.loc[0:3,['total_bill','day']]

   total_bill  day
0       16.99  Sun
1       10.34  Sun
2       21.01  Sun
3       23.68  Sun

In [14]:
df.iloc[0:3,0:3]

   total_bill   tip     sex
0       16.99  1.01  Female
1       10.34  1.66    Male
2       21.01  3.50    Male

In [15]:
df.at[0,'total_bill']

np.float64(16.99)

In [16]:
df.iat[0,0]

np.float64(16.99)

In [19]:
df[df['total_bill']>40.00]

     total_bill    tip     sex smoker   day    time  size
59        48.27   6.73    Male     No   Sat  Dinner     4
95        40.17   4.73    Male    Yes   Fri  Dinner     4
102       44.30   2.50  Female    Yes   Sat  Dinner     3
142       41.19   5.00    Male     No  Thur   Lunch     5
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
182       45.35   3.50    Male    Yes   Sun  Dinner     3
184       40.55   3.00    Male    Yes   Sun  Dinner     2
197       43.11   5.00  Female    Yes  Thur   Lunch     4
212       48.33   9.00    Male     No   Sat  Dinner     4

In [21]:
df[(df['total_bill']>40) & (df['sex']=='Male')]

     total_bill    tip   sex smoker   day    time  size
59        48.27   6.73  Male     No   Sat  Dinner     4
95        40.17   4.73  Male    Yes   Fri  Dinner     4
142       41.19   5.00  Male     No  Thur   Lunch     5
156       48.17   5.00  Male     No   Sun  Dinner     6
170       50.81  10.00  Male    Yes   Sat  Dinner     3
182       45.35   3.50  Male    Yes   Sun  Dinner     3
184       40.55   3.00  Male    Yes   Sun  Dinner     2
212       48.33   9.00  Male     No   Sat  Dinner     4

In [25]:
df.query("tip>4 and sex=='Female'")

     total_bill   tip     sex smoker   day    time  size
11        35.26  5.00  Female     No   Sun  Dinner     4
52        34.81  5.20  Female     No   Sun  Dinner     4
73        25.28  5.00  Female    Yes   Sat  Dinner     2
85        34.83  5.17  Female     No  Thur   Lunch     4
93        16.32  4.30  Female    Yes   Fri  Dinner     2
104       20.92  4.08  Female     No   Sat  Dinner     2
125       29.80  4.20  Female     No  Thur   Lunch     6
143       27.05  5.00  Female     No  Thur   Lunch     6
155       29.85  5.14  Female     No   Sun  Dinner     5
191       19.81  4.19  Female    Yes  Thur   Lunch     2
197       43.11  5.00  Female    Yes  Thur   Lunch     4
214       28.17  6.50  Female    Yes   Sat  Dinner     3
238       35.83  4.67  Female     No   Sat  Dinner     3